### ISSUE TITLE
这个统计能起效吗?

### ISSUE THREAD

**Issue by lichenabson** [joehecn/electron-baidu-tongji#5]
我按介绍接入这个库. 但是没有效果. 
看了下这个源码, 不太理解这个源码为什么能起效, 
![image](https://user-images.githubusercontent.com/20200267/50818642-99d35f00-1362-11e9-8b90-73c129b3005f.png)这边往主进程上发事件, 但是这个ebtMain方法没有被调用过, 所以方法到这边就断了

**Comment by joehecn** [comment]
在 README 中写到了 ebtMain 这样调用：
``` js
// main/index.js
import { ipcMain } from 'electron'
import { ebtMain } from 'electron-baidu-tongji'

ebtMain(ipcMain)
```
